PeerOrgs:
- Name: peerOrg0
  Domain: peerOrg0
  EnableNodeOUs: false
  Users:
    Count: 3
    Names:
    - borrower

  Specs:
  - Hostname: borrower
    CommonName: borrower
    SANS:
    - localhost
    - 127.0.0.1
    - ::1
    - borrower

- Name: peerOrg3
  Domain: peerOrg3
  EnableNodeOUs: false
  Users:
    Count: 1
    Names:
    - lender

  Specs:
  - Hostname: lender
    CommonName: lender
    SANS:
    - localhost
    - 127.0.0.1
    - ::1
    - lender

- Name: peerOrg1
  Domain: peerOrg1
  Users:
    Count: 1
    Names:
    - approver

  Specs:
  - Hostname: approver
    CommonName: approver
    SANS:
    - localhost
    - 127.0.0.1
    - ::1
    - approver
    - host.docker.internal
