---
OrdererOrgs:
- Name: OrdererOrg
  Domain: example.com
  EnableNodeOUs: false
  CA:
    Hostname: ca
  Specs:
  - Hostname: orderer
    SANS:
    - localhost
    - 127.0.0.1
    - host.docker.internal
    - fabric
    - ::1

PeerOrgs:
- Name: Org2
  Domain: org2.example.com
  EnableNodeOUs: false
  CA:
    hostname: ca
    SANS:
    - localhost
    - 127.0.0.1
    - ::1
  Users:
    Count: 1
    Names:
    - borrower
    - User1
    - User2

  Specs:
  - Hostname: Org2_peer_0
    SANS:
    - localhost
    - 127.0.0.1
    - ::1
    - fabric
    - host.docker.internal
  - Hostname: borrower
    SANS:
    - localhost
    - 127.0.0.1
    - ::1
    - fabric
    - host.docker.internal
- Name: Org3
  Domain: org3.example.com
  EnableNodeOUs: false
  CA:
    hostname: ca
    SANS:
    - localhost
    - 127.0.0.1
    - ::1
  Users:
    Count: 1
    Names:
    - lender
    - User1
    - User2

  Specs:
  - Hostname: Org3_peer_0
    SANS:
    - localhost
    - 127.0.0.1
    - ::1
    - fabric
    - host.docker.internal
  - Hostname: lender
    SANS:
    - localhost
    - 127.0.0.1
    - ::1
    - fabric
    - host.docker.internal
- Name: Org1
  Domain: org1.example.com
  EnableNodeOUs: false
  CA:
    hostname: ca
    SANS:
    - localhost
    - 127.0.0.1
    - ::1
  Users:
    Count: 1
    Names:
    - approver
    - User1
    - User2

  Specs:
  - Hostname: Org1_peer_0
    SANS:
    - localhost
    - 127.0.0.1
    - ::1
    - fabric
    - host.docker.internal
  - Hostname: approver
    SANS:
    - localhost
    - 127.0.0.1
    - ::1
    - fabric
    - host.docker.internal
