/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradlegateway;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;

import org.hyperledger.fabric.gateway.*;


public class Library {
	public static void main(String[] args) throws IOException, ContractException {
		final String basePath = "/home/dave/testclient";
		Path walletLoc = Paths.get(basePath, "local_fabric_wallet");
		Wallet wallet = Wallet.createFileSystemWallet(walletLoc);
		
		Path ccpLoc = Paths.get(basePath, "local_fabric_connection.json");
		
		Gateway.Builder builder = Gateway.createBuilder();
		builder.discovery(true).networkConfig(ccpLoc).identity(wallet, "admin");
		try (Gateway gateway = builder.connect()) {
			
			Network network = gateway.getNetwork("mychannel");
			Contract contract = network.getContract("fred");
			contract.evaluateTransaction("KILLER", "dave", "joy");
		}
		// Gateways are AutoCloseable when used in a try with resources block
		// Alternatively you can do Gateway.close()
	}
	
	
}
